name: Nuget Uupdatge

on:
  workflow_dispatch:
    inputs:
      pe-stable:
        description: "Update Payment Engine to Stable?"
        required: true
        default: "Yes"
        type: choice
        options:
          - "Yes"
          - "No"

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  create-rc:
    runs-on: ubuntu-latest
    
      
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Install Update Tool
        run: dotnet tool install --global dotnet-outdated-tool

      - name: Verify Build
        # Ensuring the update didn't break the VB project
        run: dotnet build xAws.vbproj --configuration Release        

        
          
