name: testing yaml codes

on: 
  workflow_dispatch:

  push:
    branches:
      - "mvaldez-ck-patch-1" 

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  create-rc:
    runs-on: ubuntu-latest
    
      
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Check code
        run: |
          if [ "${{ inputs.pe-stable }}" = "Yes" ]; then
            echo "It should run pe to sable"
          else
            echo "NO pe update"
          fi          
